import { defineStore } from 'pinia'
// 定义数据仓库
import axios from 'axios'

export const useCfopStore = defineStore('cfop', {
  state: () => {
    return {
      f2l: [
        { id: 1, name: 'F2L 1', subgroups: 'Free Pairs', icon: '/cfop/icon/f2l/f2l_01.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_01.svg' },
        { id: 2, name: 'F2L 2', subgroups: 'Free Pairs', icon: '/cfop/icon/f2l/f2l_02.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_02.svg' },
        { id: 3, name: 'F2L 3', subgroups: 'Free Pairs', icon: '/cfop/icon/f2l/f2l_03.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_03.svg' },
        { id: 4, name: 'F2L 4', subgroups: 'Free Pairs', icon: '/cfop/icon/f2l/f2l_04.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_04.svg' },
        { id: 5, name: 'F2L 5', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_05.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_05.svg' },
        { id: 6, name: 'F2L 6', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_06.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_06.svg' },
        { id: 7, name: 'F2L 7', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_07.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_07.svg' },
        { id: 8, name: 'F2L 8', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_08.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_08.svg' },
        { id: 9, name: 'F2L 9', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_09.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_09.svg' },
        { id: 10, name: 'F2L 10', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_10.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_10.svg' },
        { id: 11, name: 'F2L 11', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_11.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_11.svg' },
        { id: 12, name: 'F2L 12', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_12.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_12.svg' },
        { id: 13, name: 'F2L 13', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_13.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_13.svg' },
        { id: 14, name: 'F2L 14', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_14.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_14.svg' },
        { id: 15, name: 'F2L 15', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_15.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_15.svg' },
        { id: 16, name: 'F2L 16', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_16.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_16.svg' },
        { id: 17, name: 'F2L 17', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_17.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_17.svg' },
        { id: 18, name: 'F2L 18', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_18.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_18.svg' },
        { id: 19, name: 'F2L 19', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_19.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_19.svg' },
        { id: 20, name: 'F2L 20', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_20.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_20.svg' },
        { id: 21, name: 'F2L 21', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_21.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_21.svg' },
        { id: 22, name: 'F2L 22', subgroups: 'Disconnected Pairs', icon: '/cfop/icon/f2l/f2l_22.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_22.svg' },
        { id: 23, name: 'F2L 23', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_23.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_23.svg' },
        { id: 24, name: 'F2L 24', subgroups: 'Connected Pairs', icon: '/cfop/icon/f2l/f2l_24.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_24.svg' },
        { id: 25, name: 'F2L 25', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_25.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_25.svg' },
        { id: 26, name: 'F2L 26', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_26.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_26.svg' },
        { id: 27, name: 'F2L 27', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_27.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_27.svg' },
        { id: 28, name: 'F2L 28', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_28.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_28.svg' },
        { id: 29, name: 'F2L 29', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_29.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_29.svg' },
        { id: 30, name: 'F2L 30', subgroups: 'Corner InSlot', icon: '/cfop/icon/f2l/f2l_30.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_30.svg' },
        { id: 31, name: 'F2L 31', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_31.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_31.svg' },
        { id: 32, name: 'F2L 32', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_32.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_32.svg' },
        { id: 33, name: 'F2L 33', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_33.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_33.svg' },
        { id: 34, name: 'F2L 34', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_34.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_34.svg' },
        { id: 35, name: 'F2L 35', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_35.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_35.svg' },
        { id: 36, name: 'F2L 36', subgroups: 'Edge InSlot', icon: '/cfop/icon/f2l/f2l_36.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_36.svg' },
        { id: 37, name: 'F2L 37', subgroups: 'Pieces InSlot', icon: '/cfop/icon/f2l/f2l_37.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_37.svg' },
        { id: 38, name: 'F2L 38', subgroups: 'Pieces InSlot', icon: '/cfop/icon/f2l/f2l_38.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_38.svg' },
        { id: 39, name: 'F2L 39', subgroups: 'Pieces InSlot', icon: '/cfop/icon/f2l/f2l_39.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_39.svg' },
        { id: 40, name: 'F2L 40', subgroups: 'Pieces InSlot', icon: '/cfop/icon/f2l/f2l_40.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_40.svg' },
        { id: 41, name: 'F2L 41', subgroups: 'Pieces InSlot', icon: '/cfop/icon/f2l/f2l_41.svg', algorithm: '/cfop/algorithm/f2l/f21_ai_41.svg' },
      ],
      oll: [
        { id: 1, name: 'OLL 1', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_01.svg', algorithm: '/cfop/algorithm/oll/oll_ai_01.svg' },
        { id: 2, name: 'OLL 2', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_02.svg', algorithm: '/cfop/algorithm/oll/oll_ai_02.svg' },
        { id: 3, name: 'OLL 3', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_03.svg', algorithm: '/cfop/algorithm/oll/oll_ai_03.svg' },
        { id: 4, name: 'OLL 4', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_04.svg', algorithm: '/cfop/algorithm/oll/oll_ai_04.svg' },
        { id: 5, name: 'OLL 5', subgroups: 'Square Shapes', icon: '/cfop/icon/oll/oll_05.svg', algorithm: '/cfop/algorithm/oll/oll_ai_05.svg' },
        { id: 6, name: 'OLL 6', subgroups: 'Square Shapes', icon: '/cfop/icon/oll/oll_06.svg', algorithm: '/cfop/algorithm/oll/oll_ai_06.svg' },
        { id: 7, name: 'OLL 7', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_07.svg', algorithm: '/cfop/algorithm/oll/oll_ai_07.svg' },
        { id: 8, name: 'OLL 8', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_08.svg', algorithm: '/cfop/algorithm/oll/oll_ai_08.svg' },
        { id: 9, name: 'OLL 9', subgroups: 'Fish Shapes', icon: '/cfop/icon/oll/oll_09.svg', algorithm: '/cfop/algorithm/oll/oll_ai_09.svg' },
        { id: 10, name: 'OLL 10', subgroups: 'Fish Shapes', icon: '/cfop/icon/oll/oll_10.svg', algorithm: '/cfop/algorithm/oll/oll_ai_10.svg' },
        { id: 11, name: 'OLL 11', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_11.svg', algorithm: '/cfop/algorithm/oll/oll_ai_11.svg' },
        { id: 12, name: 'OLL 12', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_12.svg', algorithm: '/cfop/algorithm/oll/oll_ai_12.svg' },
        { id: 13, name: 'OLL 13', subgroups: 'KnightMove Shapes', icon: '/cfop/icon/oll/oll_13.svg', algorithm: '/cfop/algorithm/oll/oll_ai_13.svg' },
        { id: 14, name: 'OLL 14', subgroups: 'KnightMove Shapes', icon: '/cfop/icon/oll/oll_14.svg', algorithm: '/cfop/algorithm/oll/oll_ai_14.svg' },
        { id: 15, name: 'OLL 15', subgroups: 'KnightMove Shapes', icon: '/cfop/icon/oll/oll_15.svg', algorithm: '/cfop/algorithm/oll/oll_ai_15.svg' },
        { id: 16, name: 'OLL 16', subgroups: 'KnightMove Shapes', icon: '/cfop/icon/oll/oll_16.svg', algorithm: '/cfop/algorithm/oll/oll_ai_16.svg' },
        { id: 17, name: 'OLL 17', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_17.svg', algorithm: '/cfop/algorithm/oll/oll_ai_17.svg' },
        { id: 18, name: 'OLL 18', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_18.svg', algorithm: '/cfop/algorithm/oll/oll_ai_18.svg' },
        { id: 19, name: 'OLL 19', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_19.svg', algorithm: '/cfop/algorithm/oll/oll_ai_19.svg' },
        { id: 20, name: 'OLL 20', subgroups: 'Dot Case', icon: '/cfop/icon/oll/oll_20.svg', algorithm: '/cfop/algorithm/oll/oll_ai_20.svg' },
        { id: 21, name: 'OLL 21', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_21.svg', algorithm: '/cfop/algorithm/oll/oll_ai_21.svg' },
        { id: 22, name: 'OLL 22', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_22.svg', algorithm: '/cfop/algorithm/oll/oll_ai_22.svg' },
        { id: 23, name: 'OLL 23', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_23.svg', algorithm: '/cfop/algorithm/oll/oll_ai_23.svg' },
        { id: 24, name: 'OLL 24', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_24.svg', algorithm: '/cfop/algorithm/oll/oll_ai_24.svg' },
        { id: 25, name: 'OLL 25', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_25.svg', algorithm: '/cfop/algorithm/oll/oll_ai_25.svg' },
        { id: 26, name: 'OLL 26', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_26.svg', algorithm: '/cfop/algorithm/oll/oll_ai_26.svg' },
        { id: 27, name: 'OLL 27', subgroups: 'OCLL', icon: '/cfop/icon/oll/oll_27.svg', algorithm: '/cfop/algorithm/oll/oll_ai_27.svg' },
        { id: 28, name: 'OLL 28', subgroups: 'AllCorners Oriented', icon: '/cfop/icon/oll/oll_28.svg', algorithm: '/cfop/algorithm/oll/oll_ai_28.svg' },
        { id: 29, name: 'OLL 29', subgroups: 'Awkward Shapes', icon: '/cfop/icon/oll/oll_29.svg', algorithm: '/cfop/algorithm/oll/oll_ai_29.svg' },
        { id: 30, name: 'OLL 30', subgroups: 'Awkward Shapes', icon: '/cfop/icon/oll/oll_30.svg', algorithm: '/cfop/algorithm/oll/oll_ai_30.svg' },
        { id: 31, name: 'OLL 31', subgroups: 'P Shapes', icon: '/cfop/icon/oll/oll_31.svg', algorithm: '/cfop/algorithm/oll/oll_ai_31.svg' },
        { id: 32, name: 'OLL 32', subgroups: 'P Shapes', icon: '/cfop/icon/oll/oll_32.svg', algorithm: '/cfop/algorithm/oll/oll_ai_32.svg' },
        { id: 33, name: 'OLL 33', subgroups: 'T Shapes', icon: '/cfop/icon/oll/oll_33.svg', algorithm: '/cfop/algorithm/oll/oll_ai_33.svg' },
        { id: 34, name: 'OLL 34', subgroups: 'C Shapes', icon: '/cfop/icon/oll/oll_34.svg', algorithm: '/cfop/algorithm/oll/oll_ai_34.svg' },
        { id: 35, name: 'OLL 35', subgroups: 'Fish Shapes', icon: '/cfop/icon/oll/oll_35.svg', algorithm: '/cfop/algorithm/oll/oll_ai_35.svg' },
        { id: 36, name: 'OLL 36', subgroups: 'W Shapes', icon: '/cfop/icon/oll/oll_36.svg', algorithm: '/cfop/algorithm/oll/oll_ai_36.svg' },
        { id: 37, name: 'OLL 37', subgroups: 'Fish Shapes', icon: '/cfop/icon/oll/oll_37.svg', algorithm: '/cfop/algorithm/oll/oll_ai_37.svg' },
        { id: 38, name: 'OLL 38', subgroups: 'W Shapes', icon: '/cfop/icon/oll/oll_38.svg', algorithm: '/cfop/algorithm/oll/oll_ai_38.svg' },
        { id: 39, name: 'OLL 39', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_39.svg', algorithm: '/cfop/algorithm/oll/oll_ai_39.svg' },
        { id: 40, name: 'OLL 40', subgroups: 'Lightning Shapes', icon: '/cfop/icon/oll/oll_40.svg', algorithm: '/cfop/algorithm/oll/oll_ai_40.svg' },
        { id: 41, name: 'OLL 41', subgroups: 'Awkward Shapes', icon: '/cfop/icon/oll/oll_41.svg', algorithm: '/cfop/algorithm/oll/oll_ai_41.svg' },
        { id: 42, name: 'OLL 42', subgroups: 'Awkward Shapes', icon: '/cfop/icon/oll/oll_42.svg', algorithm: '/cfop/algorithm/oll/oll_ai_42.svg' },
        { id: 43, name: 'OLL 43', subgroups: 'P Shapes', icon: '/cfop/icon/oll/oll_43.svg', algorithm: '/cfop/algorithm/oll/oll_ai_43.svg' },
        { id: 44, name: 'OLL 44', subgroups: 'P Shapes', icon: '/cfop/icon/oll/oll_44.svg', algorithm: '/cfop/algorithm/oll/oll_ai_44.svg' },
        { id: 45, name: 'OLL 45', subgroups: 'T Shapes', icon: '/cfop/icon/oll/oll_45.svg', algorithm: '/cfop/algorithm/oll/oll_ai_45.svg' },
        { id: 46, name: 'OLL 46', subgroups: 'C Shapes', icon: '/cfop/icon/oll/oll_46.svg', algorithm: '/cfop/algorithm/oll/oll_ai_46.svg' },
        { id: 47, name: 'OLL 47', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_47.svg', algorithm: '/cfop/algorithm/oll/oll_ai_47.svg' },
        { id: 48, name: 'OLL 48', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_48.svg', algorithm: '/cfop/algorithm/oll/oll_ai_48.svg' },
        { id: 49, name: 'OLL 49', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_49.svg', algorithm: '/cfop/algorithm/oll/oll_ai_49.svg' },
        { id: 50, name: 'OLL 50', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_50.svg', algorithm: '/cfop/algorithm/oll/oll_ai_50.svg' },
        { id: 51, name: 'OLL 51', subgroups: 'Line Shapes', icon: '/cfop/icon/oll/oll_51.svg', algorithm: '/cfop/algorithm/oll/oll_ai_51.svg' },
        { id: 52, name: 'OLL 52', subgroups: 'Line Shapes', icon: '/cfop/icon/oll/oll_52.svg', algorithm: '/cfop/algorithm/oll/oll_ai_52.svg' },
        { id: 53, name: 'OLL 53', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_53.svg', algorithm: '/cfop/algorithm/oll/oll_ai_53.svg' },
        { id: 54, name: 'OLL 54', subgroups: 'L Shapes', icon: '/cfop/icon/oll/oll_54.svg', algorithm: '/cfop/algorithm/oll/oll_ai_54.svg' },
        { id: 55, name: 'OLL 55', subgroups: 'Line Shapes', icon: '/cfop/icon/oll/oll_55.svg', algorithm: '/cfop/algorithm/oll/oll_ai_55.svg' },
        { id: 56, name: 'OLL 56', subgroups: 'Line Shapes', icon: '/cfop/icon/oll/oll_56.svg', algorithm: '/cfop/algorithm/oll/oll_ai_56.svg' },
        { id: 57, name: 'OLL 57', subgroups: 'AllCorners Oriented', icon: '/cfop/icon/oll/oll_57.svg', algorithm: '/cfop/algorithm/oll/oll_ai_57.svg' },
      ],
      pll: [
        { id: 1, name: 'PLL Aa', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Aa.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Aa.svg' },
        { id: 2, name: 'PLL Ab', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Ab.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ab.svg' },
        { id: 3, name: 'PLL E', subgroups: 'Opp Swap', icon: '/cfop/icon/pll/pll_E.svg', algorithm: '/cfop/algorithm/pll/pll_ai_E.svg' },
        { id: 4, name: 'PLL F', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_F.svg', algorithm: '/cfop/algorithm/pll/pll_ai_F.svg' },
        { id: 5, name: 'PLL Ga', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Ga.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ga.svg' },
        { id: 6, name: 'PLL Gb', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Gb.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Gb.svg' },
        { id: 7, name: 'PLL Gc', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Gc.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Gc.svg' },
        { id: 8, name: 'PLL Gd', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Gd.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Gd.svg' },
        { id: 9, name: 'PLL H', subgroups: 'EPLL', icon: '/cfop/icon/pll/pll_H.svg', algorithm: '/cfop/algorithm/pll/pll_ai_H.svg' },
        { id: 10, name: 'PLL Ja', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Ja.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ja.svg' },
        { id: 11, name: 'PLL Jb', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Jb.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Jb.svg' },
        { id: 12, name: 'PLL Na', subgroups: 'Opp Swap', icon: '/cfop/icon/pll/pll_Na.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Na.svg' },
        { id: 13, name: 'PLL Nb', subgroups: 'Opp Swap', icon: '/cfop/icon/pll/pll_Nb.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Nb.svg' },
        { id: 14, name: 'PLL Ra', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Ra.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ra.svg' },
        { id: 15, name: 'PLL Rb', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_Rb.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Rb.svg' },
        { id: 16, name: 'PLL T', subgroups: 'Adj Swap', icon: '/cfop/icon/pll/pll_T.svg', algorithm: '/cfop/algorithm/pll/pll_ai_T.svg' },
        { id: 17, name: 'PLL Ua', subgroups: 'EPLL', icon: '/cfop/icon/pll/pll_Ua.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ua.svg' },
        { id: 18, name: 'PLL Ub', subgroups: 'EPLL', icon: '/cfop/icon/pll/pll_Ub.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Ub.svg' },
        { id: 19, name: 'PLL V', subgroups: 'Opp Swap', icon: '/cfop/icon/pll/pll_V.svg', algorithm: '/cfop/algorithm/pll/pll_ai_V.svg' },
        { id: 20, name: 'PLL Y', subgroups: 'Opp Swap', icon: '/cfop/icon/pll/pll_Y.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Y.svg' },
        { id: 21, name: 'PLL Z', subgroups: 'EPLL', icon: '/cfop/icon/pll/pll_Z.svg', algorithm: '/cfop/algorithm/pll/pll_ai_Z.svg' },
      ],
    }
  },
  getters: {
    cards: (state) => {
      const shuffle = arr => arr.sort(() => 0.5 - Math.random())
      return shuffle(state.f2l)
    },


  },
  actions: {
    handleClick() {
      this.isChecked = !this.isChecked

    },

  },
})